### ISSUE TITLE
shim fails in WebStorm IDE when debugging

### ISSUE THREAD

**Issue by kossmoboleat** [asdf-vm/asdf-nodejs#167]
When I run a "run configuration" in WebStorm it works for normal executions, e.g. a jest test execution, but it fails to run the same run configuration in the debug mode.

When I change the path to `node` to the actual `/Users/tim/.asdf/installs/nodejs/12.16.1/bin/node` instead of simply `node` it can debug as expected. 

With the default `node` command the Webstorms debug console shows the following error, runs the test successfully but the debug connector cannot be attached...

Reshimming as suggested by the error has no effect.

```
/Users/tim/.asdf/shims/node --require /Users/tim/opt/apps/WebStorm/ch-0/201.7846.79/WebStorm.app/Contents/plugins/JavaScriptLanguage/helpers/jest-intellij/lib/jest-intellij-stdin-fix.js /Users/tim/Projects/cl/dad/ct/frontend/node_modules/jest/bin/jest.js --runInBand --colors --reporters /Users/tim/opt/apps/WebStorm/ch-0/201.7846.79/WebStorm.app/Contents/plugins/JavaScriptLanguage/helpers/jest-intellij/lib/jest-intellij-reporter.js --verbose "--testNamePattern=^CommercialRegisterExtractDetailViewComponent " --runTestsByPath /Users/tim/Projects/cl/dad/ct/frontend/src/app/components/commercial-register-extract-detail-view/commercial-register-extract-detail-view.component.spec.ts
Debugger listening on ws://127.0.0.1:54171/2415dfe3-523e-4a20-9c3d-3640c5a82110
For help, see: https://nodejs.org/en/docs/inspector
unknown command: node. Perhaps you have to reshim?
Error in JetBrains node debug connector:  Error: Command failed: /Users/tim/.asdf/shims/node /private/var/folders/tt/1477_39n6jvc6pyv8ydjdtph0000gn/T/debugConnector.201.7846.79.js
    at checkExecSyncError (child_process.js:630:11)
    at execFileSync (child_process.js:648:15)
    at Object.<anonymous> (/private/var/folders/tt/1477_39n6jvc6pyv8ydjdtph0000gn/T/debugConnector.201.7846.79.js:30:3)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1298:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:444:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 3151,
  stdout: null,
  stderr: null
}
```

**Comment by kossmoboleat** [comment]
The problem still persists. Does this have something to do with the implementation in `~/.asdf/shims/node` or `.asdf/bin/asdf itself`?

**Comment by kossmoboleat** [comment]
Now it seems to just work for me, so I'm closing the issue. I have updated asdf since the original report, so another update/fix may have fixed this.
