### ISSUE TITLE
Unable to run `npm install -g npm` on nodejs 6

### ISSUE THREAD

**Issue by Stratus3D** [asdf-vm/asdf-nodejs#304]
I've tested this with nodejs version `6.9.5` and `6.7.0` and got the same behavior on both versions. with the latest version of this nodejs plugin.

### Environment

```
OS:
Darwin home 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64

SHELL:
zsh 5.8 (x86_64-apple-darwin21.0)

ASDF VERSION:
v0.10.0-788ccab

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/Users/~/.asdf

ASDF INSTALLED PLUGINS:
clojure                      https://github.com/halcyon/asdf-clojure.git master 0b1b2bb
elasticsearch                https://github.com/asdf-community/asdf-elasticsearch.git master 3b57cc5
elixir                       ssh://git@github.com/asdf-vm/asdf-elixir.git master d08f506
erlang                       git@github.com:asdf-vm/asdf-erlang.git master 98139db
java                         https://github.com/halcyon/asdf-java.git master 77401bf
kafka                        git@github.com:JoshAshby/asdf-kafka.git master 9231d88
lua                          git@github.com:Stratus3D/asdf-lua.git master d99f76c
nodejs                       ssh://git@github.com/asdf-vm/asdf-nodejs.git master b2d06a7
postgres                     https://github.com/smashedtoatoms/asdf-postgres.git master ce9d3c6
python                       https://github.com/tuvistavie/asdf-python.git master 57ef777
rebar                        https://github.com/Stratus3D/asdf-rebar.git master a556d0c
ruby                         git@github.com:asdf-vm/asdf-ruby.git master d37b3e9
yarn                         https://github.com/twuni/asdf-yarn.git main 376c540
```
```
$ asdf nodejs nodebuild --version
node-build 4.9.63-67-g9197645d
```

### Steps to reproduce

* Install nodejs
* Run `npm install`
* Run `npm install -g npm`

### Results

Command fails and outputs the following to the log file:

```
...
5618 warn optional SKIPPING OPTIONAL DEPENDENCY: @colors/colors@1.5.0 (node_modules/npm/node_modules/@colors/colors):
5619 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/Users/~/.asdf/installs/nodejs/6.9.5/.npm/lib/node_modules/.staging/@colors/colors-22873e74' -> '/Users/~/.asdf/installs/nodejs/6.9.5/.npm/lib/node_modules/npm/node_modules/@colors/colors'
5620 verbose enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/Users/~/.asdf/installs/nodejs/6.9.5/.npm/lib/node_modules/.staging/@colors/colors-22873e74' -> '/Users/~/.asdf/installs/nodejs/6.9.5/.npm/lib/node_modules/npm/node_modules/@colors/colors'
5620 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is most likely not a problem with npm itself
5620 verbose enoent SKIPPING OPTIONAL DEPENDENCY: and is related to npm not being able to find a file.
5620 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
5621 verbose stack Error: ENOENT: no such file or directory, rename '/Users/~/.asdf/installs/nodejs/6.9.5/.npm/lib/node_modules/.staging/@gar/promisify-cb52d904' -> '/Users/~/.asdf/installs/nodejs/6.9.5/.npm/lib/node_modules/npm/node_modules/@gar/promisify'
5621 verbose stack     at destStatted (/Users/~/.asdf/installs/nodejs/6.9.5/lib/node_modules/npm/lib/install/action/finalize.js:25:7)
5621 verbose stack     at /Users/~/.asdf/installs/nodejs/6.9.5/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:264:29
5621 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
5621 verbose stack
5621 verbose stack Error: ENOENT: no such file or directory, rename '/Users/~/.asdf/installs/nodejs/6.9.5/.npm/lib/node_modules/.staging/@gar/promisify-cb52d904' -> '/Users/~/.asdf/installs/nodejs/6.9.5/.npm/lib/node_modules/npm/node_modules/@gar/promisify'
5621 verbose stack     at Error (native)
5622 verbose cwd /Users/~/devel/rnr_ui
5623 error Darwin 21.2.0
5624 error argv "/Users/~/.asdf/installs/nodejs/6.9.5/bin/node" "/Users/~/.asdf/installs/nodejs/6.9.5/bin/npm" "install" "-g" "npm"
5625 error node v6.9.5
5626 error npm  v3.10.10
5627 error path /Users/~/.asdf/installs/nodejs/6.9.5/.npm/lib/node_modules/.staging/@gar/promisify-cb52d904
5628 error code ENOENT
5629 error errno -2
5630 error syscall rename
5631 error enoent ENOENT: no such file or directory, rename '/Users/~/.asdf/installs/nodejs/6.9.5/.npm/lib/node_modules/.staging/@gar/promisify-cb52d904' -> '/Users/~/.asdf/installs/nodejs/6.9.5/.npm/lib/node_modules/npm/node_modules/@gar/promisify'
5632 error enoent ENOENT: no such file or directory, rename '/Users/~/.asdf/installs/nodejs/6.9.5/.npm/lib/node_modules/.staging/@gar/promisify-cb52d904' -> '/Users/~/.asdf/installs/nodejs/6.9.5/.npm/lib/node_modules/npm/node_modules/@gar/promisify'
5632 error enoent This is most likely not a problem with npm itself
5632 error enoent and is related to npm not being able to find a file.
5633 verbose exit [ -2, true ]

```

**Comment by augustobmoura** [comment]
I don't think this is related to `asdf-nodejs`, node v6 is a very old release node, and the latest `npm` version probably doesn't support it. I fails even in the official docker image, running `docker run node:6 npm install -g npm` also fails in the same error.

It looks like the last version of npm that doesn't throw that error is v6: `docker run node:6 npm install -g npm@6`

**Comment by Stratus3D** [comment]
Thanks! I ended up working around this issue.
