### ISSUE TITLE
Error: Cannot find module 'cdk-assume-role-credential-plugin'

### ISSUE THREAD

**Issue by MrAtheist** [asdf-vm/asdf-nodejs#315]
I'm scratching my head with another weird issue that involves cdk... 

```
$ cdk list --profile mratheist --region us-west-2
Unable to resolve plugin cdk-assume-role-credential-plugin: Error: Cannot find module 'cdk-assume-role-credential-plugin'
Require stack:
- /Users/mratheist/.asdf/installs/nodejs/16.13.1/.npm/lib/node_modules/aws-cdk/bin/cdk.js
- /Users/mratheist/.asdf/installs/nodejs/16.13.1/.npm/lib/node_modules/aws-cdk/bin/cdk
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at tryResolve (/Users/mratheist/.asdf/installs/nodejs/16.13.1/.npm/lib/node_modules/aws-cdk/bin/cdk.ts:259:24)
    at loadPlugins (/Users/mratheist/.asdf/installs/nodejs/16.13.1/.npm/lib/node_modules/aws-cdk/bin/cdk.ts:249:26)
    at initCommandLine (/Users/mratheist/.asdf/installs/nodejs/16.13.1/.npm/lib/node_modules/aws-cdk/bin/cdk.ts:267:3)
Unable to resolve plug-in: cdk-assume-role-credential-plugin


# the module is clearly under where it's supposed to be...

$ ls -la ./node_modules/cdk-assume-role-credential-plugin/
total 80
drwxr-xr-x   11 mratheist  staff    352 Sep  6 00:38 .
drwxr-xr-x  496 mratheist  staff  15872 Sep  6 00:42 ..
-rw-r--r--    1 mratheist  staff   3631 Sep  6 00:38 CHANGELOG.md
-rw-r--r--    1 mratheist  staff    309 Sep  6 00:38 CODE_OF_CONDUCT.md
-rw-r--r--    1 mratheist  staff   3306 Sep  6 00:38 CONTRIBUTING.md
-rw-r--r--    1 mratheist  staff    926 Sep  6 00:38 LICENSE
-rw-r--r--    1 mratheist  staff  13678 Sep  6 00:38 README.md
drwxr-xr-x    8 mratheist  staff    256 Sep  6 00:38 lib
drwxr-xr-x    8 mratheist  staff    256 Sep  6 00:39 node_modules
-rw-r--r--    1 mratheist  staff    860 Sep  6 00:38 package.json
-rw-r--r--    1 mratheist  staff    640 Sep  6 00:38 tsconfig.json
```

I've tried to reshim it but that didnt work, any other hack around this?

**Comment by MrAtheist** [comment]
Mitigated by removing https://github.com/aws-samples/cdk-assume-role-credential-plugin from the project as the module has been deprecated for awhile...
