### ISSUE TITLE
System npm fails to run via asdf

### ISSUE THREAD

**Issue by mclark-newvistas** [asdf-vm/asdf-nodejs#85]
`npm` works fine when I comment out `source ~/.asdf/asdf.fish` in `~/.config/fish/config.fish` and then open a new shell. When I have `asdf` enabled, I get the following. Machine is Arch Linux, up to date as of now, freshly rebooted still experiencing the issue. `asdf` is version 0.5,  and this plugin is listed as "Already up to date.".
```
$ asdf current nodejs
system  (set by /home/michael/.tool-versions)
$ npm
Error: EACCES: permission denied, mkdir '/.npm'
TypeError: Cannot read property 'get' of undefined
    at errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:76:20
    at cb (/usr/lib/node_modules/npm/lib/npm.js:228:22)
    at /usr/lib/node_modules/npm/lib/npm.js:266:24
    at /usr/lib/node_modules/npm/lib/config/core.js:83:7
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/npm/lib/config/core.js:82:13
    at f (/usr/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at afterExtras (/usr/lib/node_modules/npm/lib/config/core.js:173:20)
    at Conf.<anonymous> (/usr/lib/node_modules/npm/lib/config/core.js:229:20)
/usr/lib/node_modules/npm/lib/utils/error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at process.emit (events.js:182:13)
    at process._fatalException (internal/bootstrap/node.js:437:27)
```

**Comment by mclark-newvistas** [comment]
Of special note is that it is trying to create `/.npm`, - in `/`, instead of `~/.npm`.

**Comment by mclark-newvistas** [comment]
`.asdf/bin/private/asdf-exec` sets `$ASDF_INSTALL_PATH` to the result of `find_install_path` in `.asdf/lib/utils.sh` - which, if version is `"system"` (which it is for the system nodejs, of course), returns an empty string. This then, is passed to `.asdf/plugins/nodejs/bin/exec-env`, and, if `$NPM_CONFIG_PREFIX` is `""`, it is set to `$ASDF_INSTALL_PATH/.npm` - resulting in `"/.npm"`.

In my shell w/o `asdf` enabled which can run `npm`, `$NPM_CONFIG_PREFIX` is blank; therefore a possible patch would be to only set `$NPM_CONFIG_PREFIX` if it is blank _and_ `$ASDF_INSTALL_PATH` is _not_.
